### ISSUE TITLE
the lab server does not work alone

### ISSUE THREAD

**Issue by chunhualiao** [chunhualiao/freeCompilerCamp#88]
if we directly connect to it,  try to start a session, add an instance.   It shows no connection and a black terminal. 

![image](https://user-images.githubusercontent.com/1627206/67738359-91b8de80-f9cb-11e9-8b3d-fdf449127876.png)

We should show how to make it work and how to disable it.

**Comment by ouankou** [comment]
The reason caused this issue is that the standalone website didn't recognize the port currently used. The webpage generates a link to the websocket exposed by the sandbox and then connect to the sandbox via that link. It determines the port by Javascript, but it can't find out that we're actually using 5010 port instead of default 80 port. Thus, the generated base link doesn't specify 5010, which causes connection failure.

The reason why the training website doesn't have this issue is that it uses a preconfigured variable to set up the base link. For example, the user may provide ```freecompilercamp.org:5010``` directly as the base link.

To fix this bug, we need to manually set up the port in the file ```/www/asserts/app.js``` during the generation of base link. Please check the commit https://github.com/freeCompilerCamp/play-with-compiler/commit/5f778f0dca6a1cbf86205a5b55031df59f2b8b3a for details.
