### ISSUE TITLE
refine the port plan

### ISSUE THREAD

**Issue by chunhualiao** [chunhualiao/freeCompilerCamp#98]
the current plan for site ports is messy. Two non-standard ports are used. 

```
main :80  --forwarded to--> main: 5020 : class-room 

main: 5010   l2 -->PWD

```

Idealy, the plan should just try to match standard and default ports used by PWD and class-room.
```
main:80 ---forwarded to --> main:4000  class-room website default port

main:8080 : haprox login/welcome site 

main:443: l2 -->pwd  site

```

**Comment by ouankou** [comment]
Original PWD deploys their training website on the GitHub pages instead of individual deployment using the port 4000.
I created a similar one. Please check http://freecc.ouankou.com. It's a prototype deployed on Github pages and connected with our PWC server.

With this approach, we can worry about one less server. For updates, we commit a tutorial and wait for a short time. Then the classroom website will be regenerated automatically.

**Comment by chunhualiao** [comment]
Using gitpage is a much better solution. We should migrate to use it. Can you share some instructions so I can do it?

**Comment by ouankou** [comment]
I remember we have created a repository for this purpose. 
https://github.com/chunhualiao/freecompilercamp.github.io
We can use this one and make some changes.

1. We may use a new name, such as ```freecc-classroom``` or something else. The ```<username>.github.io``` only has a specific meaning when ```freecompilercamp``` is the owner's user name.  For example, ```freecompilercamp.github.io``` is the default domain of the official GitHub page of user ```freecompilercamp```. The particular name used by any other user won't be different than a regular name. 

![repo_name](https://user-images.githubusercontent.com/1269492/68536873-e17e9a80-0327-11ea-929e-795d7c074728.png)

2. We can create a new branch named ```gh-pages```. It will contain all the classroom files, which is the content of our ```compiler-classroom``` folder with some tweaks for GitHub pages.

3. Then we can set up the domain.
![repo_settings](https://user-images.githubusercontent.com/1269492/68536942-56060900-0329-11ea-969a-114f1a509beb.png)

  - Choose the ```gh-pages``` branch as the source of Github Pages website.
  - The theme doesn't matter. We'll leave it as is and use our own.
  - The custom domain could be ```classroom.freecompilercamp.org``` or some other proper domain for now. Later after testing, we could change it to ```freecompilercamp.org``` for the official migration. After setting up this domain, we need to set the domain on GoDaddy as well.
  - HTTPS can't be selected here. If the training website uses HTTPS, the sandbox has to use that too. However, I've worked on the PWC with HTTPS for quite a while but still can't make it work. There are a few similar issues opened on PWD github repo. The developer replied that it has nothing to do with PWD and closed them (https://github.com/play-with-docker/play-with-docker/issues/287, https://github.com/play-with-docker/play-with-docker/issues/278).

Since I'm not the owner of this repository, I can't access the setting page. If you could complete the steps mentioned above, I can update GoDaddy settings and create the GitHub pages. I must verify each step first and then document the detailed instructions.

**Comment by chunhualiao** [comment]
lets find a time in Denver to do this together.

**Comment by chunhualiao** [comment]
Ok. I think I finished all steps you mentioned.  

The repo is https://github.com/freeCompilerCamp/freeCompilerCamp.github.io 

It may take a bit time to be effective. 

![image](https://user-images.githubusercontent.com/1627206/68539304-36c1a880-0336-11ea-9e40-64afa829ab7f.png)

**Comment by chunhualiao** [comment]
@ouankou I may need your help for domain name set up. 
It is been quite a while and still not working. 

```
 dig training.freecompilercamp.org  +nostats +nocomments +nocmd

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> training.freecompilercamp.org +nostats +nocomments +nocmd
;; global options: +cmd
;training.freecompilercamp.org. IN      A
freecompilercamp.org.   71      IN      SOA     ns19.domaincontrol.com. dns.jomax.net. 2019110901 28800 7200 604800 600
```

**Comment by chunhualiao** [comment]
https://freecompilercamp.github.io/ is up and running. But terminal does not show up. 
We should try to migrate to use it so we have a much simpler deployment workflow.

**Comment by chunhualiao** [comment]
I fixed the issues. http://training.freecompilercamp.org/ now works with gitpages.

**Comment by chunhualiao** [comment]
Ok. We are moving to https://github.com/freeCompilerCamp , with two separated repos, two separated servers. Much better port plan.
